// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CustomButton: typeof import('./src/components/CustomButton.vue')['default']
    CustomInputField: typeof import('./src/components/CustomInputField.vue')['default']
    CustomNavBar: typeof import('./src/components/CustomNavBar.vue')['default']
    ErrorIndicator: typeof import('./src/components/ErrorIndicator.vue')['default']
    FavoriteBookmarkCard: typeof import('./src/components/cards/FavoriteBookmarkCard.vue')['default']
    FoodRecipesCard: typeof import('./src/components/cards/FoodRecipesCard.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Login: typeof import('./src/components/auth/Login.vue')['default']
    RecipeDetailComments: typeof import('./src/components/recipe_detail/RecipeDetailComments.vue')['default']
    RecipeDetailDesc: typeof import('./src/components/recipe_detail/RecipeDetailDesc.vue')['default']
    RecipeDetailDirections: typeof import('./src/components/recipe_detail/RecipeDetailDirections.vue')['default']
    RecipeDetailImages: typeof import('./src/components/recipe_detail/RecipeDetailImages.vue')['default']
    RecipeDetailRating: typeof import('./src/components/recipe_detail/RecipeDetailRating.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchRecipesInput: typeof import('./src/components/SearchRecipesInput.vue')['default']
    SelectCategory: typeof import('./src/components/SelectCategory.vue')['default']
    SignUp: typeof import('./src/components/auth/SignUp.vue')['default']
  }
}

export {}
